name: "Build and Deploy dbt Models"
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
env:
  PROJECT_ID: "new-map-project-1538399427267"
  REGION: "us-central1"
  IMAGE_NAME: "dbt_test"
  REPOSITORY: "dbt-images"
  JOB_NAME: "dbt_test_job_c_run"
  WORKFLOW_NAME: "dbt_test_workflow_new"
  DEPLOYER_SERVICE_ACCOUNT: 'github-actions-dbt@new-map-project-1538399427267.iam.gserviceaccount.com'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/995265336172/locations/global/workloadIdentityPools/github-dbt-pool/providers/github-dbt-provider'
        service_account: 'github-actions-dbt@new-map-project-1538399427267.iam.gserviceaccount.com'
        token_format: 'access_token'
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - uses: docker/build-push-action@v5
      with:
        context: ./dbt_airflow_test
        file: ./dbt_airflow_test/Dockerfile
        push: true
        tags: |
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
    - name: Update GCP Cloud Run Job
      run: |
        gcloud run jobs update ${{ env.JOB_NAME }} \
          --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --project=${{ env.PROJECT_ID }} \
          --region=${{ env.REGION }}
    - name: Deploy Workflow Definition
      if: ${{ env.WORKFLOW_NAME != '' }}
      run: |
        gcloud workflows deploy ${{ env.WORKFLOW_NAME }} \
          --source=config/workflow.yaml \
          --location=${{ env.REGION }} \
          --project=${{ env.PROJECT_ID }}